### ISSUE TITLE
Talend 8 - java.lang.NoSuchFieldException: mdc

### ISSUE THREAD

**Issue by Jens2205** [jlolling/talendcomp_tJasperServerFile#12]
Hi Jan,

we discovered a potential issue in our environment while using Talend Studio 8 with Java 11.

Recently, we've been experiencing the following error message:
` java.lang.NoSuchFieldException: mdc
	at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
	at org.apache.log4j.MDCFriend.fixForJava9(MDCFriend.java:13)
	at org.slf4j.log4j12.Log4jMDCAdapter.<clinit>(Log4jMDCAdapter.java:38)
	at org.slf4j.log4j12.Log4j12ServiceProvider.initialize(Log4j12ServiceProvider.java:37)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:153)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:419)`

After some investigation, we suspect that this issue may be related to the use of Log4j2 within our Talend Studio 8 environment and the usage of the component tJasperServerFilePut.

Thank you for your attention to this matter, and we look forward to your feedback.

Best regards,
Susanne & Jens

**Comment by jlolling** [comment]
Your findings are correct. I have still log4j version 1 in use here. I will replace log4j v1 with log4j v2 and remove slf4j because it does not help here.

**Comment by jlolling** [comment]
You can download find the updated components here: https://github.com/jlolling/talendcomp_tJasperServerFile/releases
It would be great to have feedback.

**Comment by skoeper23** [comment]
Hi Jan,

thank you for your quick support! It works now.

The component tJasperServerFilePut asked vor the following jars: 
- jackson-annotations-2.13.4.jar
- jackson-core-2.13.4.jar
- jackson-databind-2.13.4.jar
- jlo-talendcomp-jasperserverfile-2.9.jar
I found them all in your component folder. After installing them it worked.

Best regards
Susanne

**Comment by Jens2205** [comment]
Hi Jan,

thank's for your help! It works fine now :-)

We have just to add the jars Susanne mention.

Best regards
Jens

**Comment by jlolling** [comment]
Actually all jars should be installed automatically.
